# 战斗场景配置
# 用于精细化CEV计算的不同战斗场景

scenarios:
  vs_elite:
    name: "对精英单位"
    description: "少量高血量目标，如英雄单位、BOSS"
    target_avg_hp: 200
    target_count: 3
    target_armor: 2
    importance_weight: 0.3
    
  vs_swarm:
    name: "对虫群"
    description: "大量低血量目标，如跳虫、陆战队员"
    target_avg_hp: 50
    target_count: 20
    target_armor: 0
    importance_weight: 0.2
    
  vs_mixed:
    name: "对混合部队"
    description: "中等数量中等血量，最常见的战斗场景"
    target_avg_hp: 100
    target_count: 8
    target_armor: 1
    importance_weight: 0.4
    
  vs_armored:
    name: "对重甲部队"
    description: "重甲单位如坦克、雷神"
    target_avg_hp: 150
    target_count: 5
    target_armor: 2
    vs_attribute: "重甲"
    importance_weight: 0.1

# 地图类型修正
map_modifiers:
  open_field:
    name: "开阔地形"
    range_importance: 1.2
    mobility_importance: 0.8
    
  choke_point:
    name: "关口防守"
    range_importance: 0.8
    aoe_importance: 1.5
    
  urban:
    name: "城市战"
    range_importance: 0.6
    mobility_importance: 1.2

# 游戏阶段
game_phases:
  early:
    name: "前期"
    time_minutes: [0, 10]
    lambda_factor: 0.3
    
  mid:
    name: "中期"
    time_minutes: [10, 20]
    lambda_factor: 0.593
    
  late:
    name: "后期"
    time_minutes: [20, 40]
    lambda_factor: 0.9