# 五大精英单位对比排名实验

name: "五大精英单位对比排名"
type: "unit_eval"
description: "对诺娃、斯旺、德哈卡、阿塔尼斯、阿拉纳克的五个新更新的精英单位进行全面评估和排名"

# 模型配置
model_version: "v2.1"
cev_version: "dynamic"
cem_enabled: true

# 评估所有指挥官
commanders:
  - "诺娃"
  - "斯旺"
  - "德哈卡"
  - "阿塔尼斯"
  - "阿拉纳克"

# 评估所有单位（空列表表示使用所有）
units: 
  - "RaidLiberator"
  - "SiegeTank_Swann"
  - "Impaler"
  - "Dragoon"
  - "Wrathwalker"

# 游戏阶段
game_phases:
  - "early_game"   # 3分钟
  - "mid_game"     # 10分钟
  - "late_game"    # 20分钟

# 环境参数
population_cap: 200
resource_multiplier: 1.0

# 运行参数
num_runs: 1
random_seed: 42

# 输出设置
save_plots: true
save_raw_data: true
generate_report: true

# 额外参数
extra_params:
  # 评估上下文
  context:
    n_support: 2      # 支援单位数
    n_ally: 15        # 盟友单位数
    
  # 排名设置
  ranking:
    top_n_per_phase: 5       # 每个阶段显示前N名
    separate_by_commander: false # 按指挥官分别排名
    include_free_units: false    # 是否包含免费单位
    
  # 可视化设置
  plot_settings:
    figure_size: [14, 10]
    dpi: 300
    color_scheme: "viridis"
    create_tier_list: true      # 创建分级表
    create_scatter_plots: true  # 创建散点图
    create_heatmaps: true      # 创建热力图 